### ISSUE TITLE
getWidth()/getHeight() incorrect value or rounding error

### ISSUE THREAD

**Issue by john-kelly** [codehs/chs-js-lib#100]
**Describe the bug**
`getWidth()/getHeight()` doesnt produce correct value in some cases.

**To Reproduce**
https://codehs.com/sandbox/andy/genuary-18-1

**Expected behavior**
Should not error.

**Screenshots**
![image](https://user-images.githubusercontent.com/4268509/150015594-e1c6372b-df42-44f9-8d2d-8a9dbb763e97.png)

**Desktop (please complete the following information):**
Chrome Version 96.0.4664.110 (Official Build) (arm64)

**Comment by anderoonies** [comment]
@all-contributors recognize @john-kelly for bug report

**Comment by anderoonies** [comment]
@all-contributors please add @john-kelly for bug report
