### ISSUE TITLE
[Feature] Re-implement `waitForClick()` in new lib

### ISSUE THREAD

**Issue by zgalant** [codehs/chs-js-lib#135]
**Is your feature request related to a problem? Please describe.**
This was supported in the old JS lib (although maybe not taught)
My old helicopter game uses it https://codehs.com/sandbox/zach/Helicopter

**Describe the solution you'd like**
We could implement this in a similar way to pause all graphics timers while waiting

**Comment by anderoonies** [comment]
It still exists in the library! Just not consumed by CodeHS, didn't know it was needed anywhere. 
I'll have a fix up today.

**Comment by anderoonies** [comment]
This is closed, it's now available in CodeHS (no need for a change here)

**Comment by zgalant** [comment]
dont prioritize. not important i just wanted it logged  





On Wed, Mar 9, 2022 at 10:42 AM Andy Bayer ***@***.***>  wrote:


It still exists in the library! Just not consumed by CodeHS, didn't know it was
needed anywhere.
I'll have a fix up today.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS  or Android. 
You are receiving this because you authored the thread.Message ID: 
***@***.***>



Zach Galant
***@***.*** |LinkedIn
